### ISSUE TITLE
Check if user has entered a Valid City name first

### ISSUE THREAD

**Issue by shiv19** [dabit3/gpt-travel-advisor#5]
@dabit3 Nice app! I would suggest to check if the user entered a valid city name, if not then ask them to try again.
<img width="867" alt="image" src="https://user-images.githubusercontent.com/9407019/217108522-cbd58007-49f9-438a-80f1-ab02a4a59953.png">

**Comment by merouanezouaid** [comment]
LOL from trip advisor to a master chef
good comment

**Comment by dabit3** [comment]
ha thanks for this, I think I've made some updates to somewhat prevent this to an extent, not a perfect solution but works so far
